title: I M ZX
description: My Personal Blog
author: Zhangxiang
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/GITxiangzhang
about: 小小前端攻城狮

baseurl: "https://gitxiangzhang.github.io/xiangzhang.github.io"
url: "https://gitxiangzhang.github.io/xiangzhang.github.io"

allowsearch: true

disqus_shortname: zhangxiang
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
