# Site settings
title: I M ZX
description: "A blog about lorem ipsum ..."
baseurl: "/xiangzhang.github.io" # for test: remove string '/space-jekyll-templa' to ''
url: "https://gitxiangzhang.github.io/xiangzhang.github.io/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'
# User settings
username: xiangzhang
user_title: Zhang xiang- FrontEnd
email: 1213086100@qq.com
twitter_username: xiangzhang
github_username:  GITxiangzhang
gplus_username:  xiangzhang
disqus_username: xiangzhang
profile_picture: https://68.media.tumblr.com/93f384858e9273d5b980b418e2f2f4d5/tumblr_o5i2aybLJG1uapsfmo2_250.png

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
#projects:
#  - name: asciilang
#    url: https://github.com/victorvoid/asciilang
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
